### ISSUE TITLE
Shortcut buttons from homepage are missing the proper hyperlink and not working 

### ISSUE THREAD

**Issue by vdeparday** [riskinfo-lk/riskinfo_lk#15]
All the icones on the homepage don't link to the right pages, the hazard ones link to standard:
http://www.riskinfo.lk/search/ when they should actually filter based on the search

Some icons like administrative boundaries have not been changed since reusing the labs template, for instance:
http://www.riskinfo.lk/search/?title__icontains=haiyan

**Comment by rbanick** [comment]
Still a problem, now all links go to Hazard

**Comment by GeoEDGE** [comment]
Corrected the links for the relevant filters.
