### ISSUE TITLE
Homepage Tsunami Time Travel Map source link is not working and the background is white

### ISSUE THREAD

**Issue by vdeparday** [riskinfo-lk/riskinfo_lk#16]
The Tsunami Time Travel Map is just a screenshot of the previous one, it should be an image + an hyperlink to the source like it was in the previous one (See http://203.115.15.232/)
This way the background will be of the same color and the source will be actually be hyperlinked.

**Comment by vdeparday** [comment]
It is nice now the source is hyperlinked but the source link is in the middle of the page, see below:

![image](https://cloud.githubusercontent.com/assets/1036189/11122994/b5e9ec1c-896e-11e5-8744-483845418c1c.png)

**Comment by rbanick** [comment]
@vdeparday can you provide a link to the actual source? I'm afraid this was before my time and I don't understand.

**Comment by rbanick** [comment]
I'm assuming this is old and closing this unless @vdeparday clarifies
