### ISSUE TITLE
Wrong ratio for the Riskinfo Logo

### ISSUE THREAD

**Issue by vdeparday** [riskinfo-lk/riskinfo_lk#17]
The RiskInfo Logo looks compressed on the horizontal dimension. Even if we make it a bit smaller, we need to keep the image ratio the same as on http://203.115.15.232/

**Comment by rbanick** [comment]
We should close this as it refers to the old design

**Comment by vdeparday** [comment]
Can you close them? Do you need to get admin right?

**Comment by vdeparday** [comment]
Added you as admin and closing this one.
