### ISSUE TITLE
Language switcher is not available

### ISSUE THREAD

**Issue by vdeparday** [riskinfo-lk/riskinfo_lk#18]
There is no language switcher anywhere on the page. We should create this functionality with a similar look to core GeoNode. It should be possible to switch between English, Sinhala and Tamil.

**Comment by GeoEDGE** [comment]
Completed
![untitled](https://cloud.githubusercontent.com/assets/19869158/16646700/250f3eb8-4449-11e6-9742-cb932380ba41.png)

**Comment by vdeparday** [comment]
It would be great to have two little improvements:
1) Could we spell Sinhala with the Sinhalese alphabet and Tamil with the Tamil alphabet? (like in the screenshot below)
2) If it doesn't wreck up the design, could we make it so that all language are displayed up front like it was in the first version below?

Thanks !

![image](https://cloud.githubusercontent.com/assets/1036189/17368170/e82f5dd4-5960-11e6-9cf7-b8498fada65f.png)

**Comment by GeoEDGE** [comment]
Completed

![risk](https://cloud.githubusercontent.com/assets/19869158/17424729/6c02119a-5ae4-11e6-90b6-7dfe8bdf478f.png)
