### ISSUE TITLE
Add Bing, Humanitarian OSM, Google Maps, OSM Greyscale as basemap options

### ISSUE THREAD

**Issue by vdeparday** [riskinfo-lk/riskinfo_lk#23]
We can remove Mapquest imagery too. We can also add some options for Google Maps background.

**Comment by rbanick** [comment]
Let's also add the Humanitarian OSM layer as an option

**Comment by GeoEDGE** [comment]
**Bing,Humanitarian OSM and OSM Greyscale** layers are added as **basemap** options.
