### ISSUE TITLE
Styles editor not working

### ISSUE THREAD

**Issue by rbanick** [riskinfo-lk/riskinfo_lk#24]
The styles editor for layers allows you to change layer colors in its dialogue box but the changes aren't saved or reflected on the map. When you exit the editor the map stays the same and when you reload the colors reset to the previous color.

**Comment by GeoEDGE** [comment]
Layer styles are saving to the map, but it raises an error when publishing a map.

**Comment by rbanick** [comment]
Can we mark this closed now? @GeoEDGE

**Comment by GeoEDGE** [comment]
Can you keep it open, as there is this layer http://riskinfo.lk/layers/geonode%3ASri_Lanka_WGS84
that doesn't reflect the style changes on the layer, I am finding where the bug is, shall give an 
update soon.

**Comment by rbanick** [comment]
OK

**Comment by GeoEDGE** [comment]
There was an issue with the above layer's thumbnail image ownership as the layer wasn't created through  geonode upload interface but executing updatelayers command and wasn't set shapefile path correctly.
This bug is fixed now.
