### ISSUE TITLE
ICTA Server VPN Connection Issues

### ISSUE THREAD

**Issue by rbanick** [riskinfo-lk/riskinfo_lk#34]
We've had repeated issues accessing the VPN via the ICTA server. We should document these issues here and then speak with ICTA about resolving them.

**Comment by srimalsl** [comment]
Got it solved. This problem some times happen when it run through Windows.  You have to right click and "Run as Administrator" to avoid this problem and then its working.

**Comment by rbanick** [comment]
Good catch! We should note this in the RiskInfo Handbook when it comes time to update.
