### ISSUE TITLE
Setup google analytics and django-request

### ISSUE THREAD

**Issue by rbanick** [riskinfo-lk/riskinfo_lk#35]
We want to collect basic information and stats about our users. This should be a vanilla deployment, very simple. We'll have custom GeoNode analytics in a few months time so we don't want to invest too much in anything special right now.

**Comment by GeoEDGE** [comment]
Completed. We configured the google analytics with the given gmail account from DMC (Srimal).
find the below screenshot of analytics.
![capture](https://cloud.githubusercontent.com/assets/19869158/16643293/d3e79f84-4430-11e6-8b34-2a72298a078b.PNG)
