### ISSUE TITLE
Request download causes error

### ISSUE THREAD

**Issue by rbanick** [riskinfo-lk/riskinfo_lk#38]
I tried to download the "Population in 500m tsunami" layer today and received a generic error message. See screenshot below. Also note that I am an admin and shouldn't have to request permission...

<img width="1312" alt="download_error_message" src="https://cloud.githubusercontent.com/assets/1583376/16840922/bb5b42ea-49df-11e6-8557-5ff3990db206.png">

**Comment by GeoEDGE** [comment]
Tried the same layer, but didn't receive any error message, Can you check it again 
and confirm, attached the downloaded layer in png format.

![populatn_dwnld](https://cloud.githubusercontent.com/assets/19869158/16871951/894af836-4aa7-11e6-9a94-0984a512b836.png)

**Comment by rbanick** [comment]
Hmmm. I just checked and it's working fine. I'll close this issue for now but reopen if it recurs.
