### ISSUE TITLE
side map in data view focused on 0,0

### ISSUE THREAD

**Issue by rbanick** [riskinfo-lk/riskinfo_lk#39]
Can we have the small side map that appears on the Layers / Maps / Documents view focus on Sri Lanka instead of 0,0? See picture below.

<img width="1016" alt="side_map" src="https://cloud.githubusercontent.com/assets/1583376/16841809/867b20f0-49e3-11e6-8fb6-070b601d38d5.png">

**Comment by GeoEDGE** [comment]
Now it is focused on Sri Lanka.
