### ISSUE TITLE
Remove MapQuest tiles, make OSM new standard

### ISSUE THREAD

**Issue by rbanick** [riskinfo-lk/riskinfo_lk#40]
Mapquest [has discontinued their tiling service](http://www.weeklyosm.eu/archives/7855) so we need to get rid of those tiles. Let's make OSM the standard instead. If the Humanitarian OSM Layer is not already in there let's make sure that's up too.

**Comment by GeoEDGE** [comment]
Removed Mapquest Base Map options, OSM is the default Base Map.

**Comment by vdeparday** [comment]
Also, there is a thread on GeoNode mailing list with a fix.
