### ISSUE TITLE
Add powered by GeoNode

### ISSUE THREAD

**Issue by vdeparday** [riskinfo-lk/riskinfo_lk#44]
Beside developed by GeoEdge

![image](https://cloud.githubusercontent.com/assets/1036189/17441592/cdf7a4a8-5aff-11e6-82ce-a24c1e4971a6.png)

Could we add link similar to the standard GeoNode:

![image](https://cloud.githubusercontent.com/assets/1036189/17441612/e7d678c2-5aff-11e6-87b9-75bec8be3c55.png)

To give credits and for people to know. Thank you !

**Comment by GeoEDGE** [comment]
added to the footer. let us know if you want to change the position of it.
