### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by vdeparday** [riskinfo-lk/riskinfo_lk#45]
![image](https://cloud.githubusercontent.com/assets/1036189/17754048/ba451422-64a0-11e6-93e4-f6204153ae66.png)

**Comment by GeoEDGE** [comment]
Done.
![capture](https://cloud.githubusercontent.com/assets/19869158/17771590/6c84df6c-6561-11e6-8cc8-0cfdc923e8b9.PNG)
